export const GET_SERVER_CHOICE_REQUEST = 'GET_SERVER_CHOICE_REQUEST'
export const GET_SERVER_CHOICE_RESPONSE = 'GET_SERVER_CHOICE_RESPONSE'
export const GET_SERVER_CHOICE_ERROR = 'GET_SERVER_CHOICE_ERROR'
